[[files]]
source = '../../files/user-dirs-bluewy@raphael/user-dirs.dirs'
target = '/home/bluewy/.config/user-dirs.dirs'
action = 'link'
chmod = '644'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel', 'bluewy@sariel']

[[files]]
source = '../../files/user-dirs-bluewy@raphael/user-dirs.dirs'
target = '/home/yellowy/.config/user-dirs.dirs'
action = 'link'
chmod = '644'
owner = 'bluewy'
group = 'bluewy'
profiles = ['yellowy@uriel']
