[[packages]]
install = [
   { from = 'std', name = 'amd-ucode' },
   { from = 'std', name = 'linux-firmware' },

   { from = 'std', name = 'linux-cachyos' },
   { from = 'std', name = 'linux-cachyos-lts' },

   { from = 'std', name = 'lact' },

   # by chwd
   #
   { from = 'std', name = 'lib32-audit' },
   { from = 'std', name = 'lib32-libcap' },
   { from = 'std', name = 'lib32-libgcrypt' },
   { from = 'std', name = 'lib32-libgpg-error' },
   { from = 'std', name = 'lib32-libnsl' },
   { from = 'std', name = 'lib32-libtirpc' },
   { from = 'std', name = 'lib32-pam' },
   { from = 'std', name = 'lib32-systemd' },
   { from = 'std', name = 'lib32-vulkan-icd-loader' },
   { from = 'std', name = 'lib32-vulkan-mesa-device-select' },
   { from = 'std', name = 'lib32-xcb-util-keysyms' },
   { from = 'std', name = 'gst-plugin-va' },
   { from = 'std', name = 'lib32-vulkan-radeon' },

   { from = 'std', name = 'lib32-opencl-mesa' },
   { from = 'std', name = 'xf86-video-amdgpu' },
]
profiles = ['root@belphegor']
